In [9]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

In [10]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /root/miniconda3/lib/python3.10/site-packages (1.3.1)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /root/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.24.4)
Requirement already satisfied: scipy>=1.5.0 in /root/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /root/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /root/miniconda3/lib/python3.10/site-packages (from scikit-learn) (3.2.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [11]:
import pandas as pd

df = pd.read_csv('data/data_for_project.csv', sep=';')

print(df) 
df.info

                  HourUTC            HourDK PriceArea  ConsumerType_DE35  \
0        2023-06-30 21:00  2023-06-30 23:00       DK1                111
1        2023-06-30 21:00  2023-06-30 23:00       DK2                111
2        2023-06-30 21:00  2023-06-30 23:00       DK1                112
3        2023-06-30 21:00  2023-06-30 23:00       DK2                112
4        2023-06-30 21:00  2023-06-30 23:00       DK1                119
...                   ...               ...       ...                ...
1997275  2020-06-30 22:00  2020-07-01 00:00       DK2                447
1997276  2020-06-30 22:00  2020-07-01 00:00       DK2                450
1997277  2020-06-30 22:00  2020-07-01 00:00       DK2                461
1997278  2020-06-30 22:00  2020-07-01 00:00       DK2                462
1997279  2020-06-30 22:00  2020-07-01 00:00       DK2                999

         TotalCon
0           65920
1           47018
2            1313
3             933
4           21806
...           ...
1997275     18735
1997276      8243
1997277     20853
1997278     10187
1997279    326440

[1997280 rows x 5 columns]

<bound method DataFrame.info of                   HourUTC            HourDK PriceArea  ConsumerType_DE35  \
0        2023-06-30 21:00  2023-06-30 23:00       DK1                111
1        2023-06-30 21:00  2023-06-30 23:00       DK2                111
2        2023-06-30 21:00  2023-06-30 23:00       DK1                112
3        2023-06-30 21:00  2023-06-30 23:00       DK2                112
4        2023-06-30 21:00  2023-06-30 23:00       DK1                119
...                   ...               ...       ...                ...
1997275  2020-06-30 22:00  2020-07-01 00:00       DK2                447
1997276  2020-06-30 22:00  2020-07-01 00:00       DK2                450
1997277  2020-06-30 22:00  2020-07-01 00:00       DK2                461
1997278  2020-06-30 22:00  2020-07-01 00:00       DK2                462
1997279  2020-06-30 22:00  2020-07-01 00:00       DK2                999

         TotalCon
0           65920
1           47018
2            1313
3             933
4           21806
...           ...
1997275     18735
1997276      8243
1997277     20853
1997278     10187
1997279    326440

[1997280 rows x 5 columns]>

In [12]:
def convert_csv_to_parquet(df, output_file_path, drop_option):
    # Read CSV file into a Pandas DataFrame

    # Remove rows or columns with NaN fields based on the drop_option argument
    if drop_option == 'row':
        df = df.dropna()
    elif drop_option == 'column':
        df = df.dropna(axis=1)

    # Convert Pandas DataFrame to PyArrow Table
    table = pa.Table.from_pandas(df)

    # Write PyArrow Table to Parquet file
    pq.write_table(table, output_file_path)

    # Open the Parquet file
    table = pq.read_table(output_file_path)

    # Convert the table to a Pandas DataFrame
    df = table.to_pandas()

    # Print the DataFrame
    print(df.head(100))

In [13]:
input_file_path = './data/data_for_project.csv'
output_file_path = './data/data_for_project.parquet'
drop_option = 'column'  # options: 'row' or 'column'
    
df = pd.read_csv(input_file_path,  sep=';')
df['HourUTC'] = df['HourUTC'].astype('datetime64[ns]')
df['HourDK'] = df['HourDK'].astype('datetime64[ns]')

df['HourUTC_year'] = df['HourUTC'].dt.year
df['HourUTC_month'] = df['HourUTC'].dt.month
df['HourUTC_day'] = df['HourUTC'].dt.day
df['HourUTC_hour'] = df['HourUTC'].dt.hour
df['HourUTC_minute'] = df['HourUTC'].dt.minute
# del df['HourUTC']

df['HourDK_year'] = df['HourDK'].dt.year
df['HourDK_month'] = df['HourDK'].dt.month
df['HourDK_day'] = df['HourDK'].dt.day
df['HourDK_hour'] = df['HourDK'].dt.hour
df['HourDK_minute'] = df['HourDK'].dt.minute
del df['HourDK']

# vectorizer = CountVectorizer()
# df['Price_Area'] = vectorizer.fit_transform(df['PriceArea'])
# del df['PriceArea']

df.PriceArea.unique()
df['PriceArea'].loc[df['PriceArea'] == 'DK1'] = 1
df['PriceArea'].loc[df['PriceArea'] == 'DK2'] = 2

# print(df.head(100))

convert_csv_to_parquet(df, output_file_path, drop_option)

/tmp/ipykernel_14526/2180382136.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PriceArea'].loc[df['PriceArea'] == 'DK1'] = 1
/tmp/ipykernel_14526/2180382136.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PriceArea'].loc[df['PriceArea'] == 'DK2'] = 2

               HourUTC  PriceArea  ConsumerType_DE35  TotalCon  HourUTC_year  \
0  2023-06-30 21:00:00          1                111     65920          2023
1  2023-06-30 21:00:00          2                111     47018          2023
2  2023-06-30 21:00:00          1                112      1313          2023
3  2023-06-30 21:00:00          2                112       933          2023
4  2023-06-30 21:00:00          1                119     21806          2023
..                 ...        ...                ...       ...           ...
95 2023-06-30 20:00:00          2                215       190          2023
96 2023-06-30 20:00:00          1                220      5910          2023
97 2023-06-30 20:00:00          2                220       964          2023
98 2023-06-30 20:00:00          1                310     64461          2023
99 2023-06-30 20:00:00          2                310     16246          2023

    HourUTC_month  HourUTC_day  HourUTC_hour  HourUTC_minute  HourDK_year  \
0               6           30            21               0         2023
1               6           30            21               0         2023
2               6           30            21               0         2023
3               6           30            21               0         2023
4               6           30            21               0         2023
..            ...          ...           ...             ...          ...
95              6           30            20               0         2023
96              6           30            20               0         2023
97              6           30            20               0         2023
98              6           30            20               0         2023
99              6           30            20               0         2023

    HourDK_month  HourDK_day  HourDK_hour  HourDK_minute
0              6          30           23              0
1              6          30           23              0
2              6          30           23              0
3              6          30           23              0
4              6          30           23              0
..           ...         ...          ...            ...
95             6          30           22              0
96             6          30           22              0
97             6          30           22              0
98             6          30           22              0
99             6          30           22              0

[100 rows x 14 columns]

In [14]:
pd.read_parquet('./data/data_for_project.parquet')

,HourUTC,PriceArea,ConsumerType_DE35,TotalCon,HourUTC_year,HourUTC_month,HourUTC_day,HourUTC_hour,HourUTC_minute,HourDK_year,HourDK_month,HourDK_day,HourDK_hour,HourDK_minute
0,2023-06-30 21:00:00,1,111,65920,2023,6,30,21,0,2023,6,30,23,0
1,2023-06-30 21:00:00,2,111,47018,2023,6,30,21,0,2023,6,30,23,0
2,2023-06-30 21:00:00,1,112,1313,2023,6,30,21,0,2023,6,30,23,0
3,2023-06-30 21:00:00,2,112,933,2023,6,30,21,0,2023,6,30,23,0
4,2023-06-30 21:00:00,1,119,21806,2023,6,30,21,0,2023,6,30,23,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997275,2020-06-30 22:00:00,2,447,18735,2020,6,30,22,0,2020,7,1,0,0
1997276,2020-06-30 22:00:00,2,450,8243,2020,6,30,22,0,2020,7,1,0,0
1997277,2020-06-30 22:00:00,2,461,20853,2020,6,30,22,0,2020,7,1,0,0
1997278,2020-06-30 22:00:00,2,462,10187,2020,6,30,22,0,2020,7,1,0,0
1997279,2020-06-30 22:00:00,2,999,326440,2020,6,30,22,0,2020,7,1,0,0

In [15]:
from datetime import datetime
import pandas as pd

from feast import FeatureStore

# Note: see https://docs.feast.dev/getting-started/concepts/feature-retrieval for 
# more details on how to retrieve for all entities in the offline store instead
entity_df = pd.DataFrame.from_dict(
    {
        # entity's join key -> entity values
        "ConsumerType_DE35_id": [111, 112, 113],
        # # "event_timestamp" (reserved key) -> timestamps
        "HourUTC": [
            datetime(2021, 4, 12, 10, 59),
            datetime(2021, 4, 12, 8, 12),
            datetime(2021, 4, 12, 16, 40),
        ],
        # values we're using for an on-demand transformation
        "val_to_add": [1, 2, 3],
        "val_to_add_2": [10, 20, 30],
    }
)

store = FeatureStore(repo_path=".")

training_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "hourly_energy_consumption:PriceArea",
        "hourly_energy_consumption:ConsumerType_DE35",
        "hourly_energy_consumption:TotalCon",
        "transformed_TotalCon:TotalCon_plus_val1",
        "transformed_TotalCon:TotalCon_plus_val2",
    ],
).to_df()

print("----- Feature schema -----\n")
print(training_df.info())

Using HourUTC as the event timestamp. To specify a column explicitly, please name it event_timestamp.
----- Feature schema -----

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ConsumerType_DE35_id  3 non-null      int64
 1   HourUTC               3 non-null      datetime64[ns, UTC]
 2   val_to_add            3 non-null      int64
 3   val_to_add_2          3 non-null      int64
 4   PriceArea             3 non-null      int64
 5   ConsumerType_DE35     3 non-null      int64
 6   TotalCon              3 non-null      int64
 7   TotalCon_plus_val1    3 non-null      int64
 8   TotalCon_plus_val2    3 non-null      int64
dtypes: datetime64[ns, UTC](1), int64(8)
memory usage: 344.0 bytes
None

In [16]:
print()
print("----- Example features -----\n")
print(training_df.head())

----- Example features -----

   ConsumerType_DE35_id                   HourUTC  val_to_add  val_to_add_2  \
0                   112 2021-04-12 08:12:00+00:00           2            20
1                   111 2021-04-12 10:59:00+00:00           1            10
2                   113 2021-04-12 16:40:00+00:00           3            30

   PriceArea  ConsumerType_DE35  TotalCon  TotalCon_plus_val1  \
0          1                111     86733               86735
1          1                111     90322               90323
2          2                370      1648                1651

   TotalCon_plus_val2
0               86753
1               90332
2                1678

In [3]:
from feast import FeatureStore

feature_store = FeatureStore(repo_path=".")
feature_vector = feature_store.get_online_features(
    entity_rows=[{"ConsumerType_DE35_id": 111}],
    features=["hourly_energy_consumption:TotalCon"]
).to_dict()
print(feature_vector)

{'ConsumerType_DE35_id': [111], 'TotalCon': [None]}